tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    label: "chore"
  - title: "🗒️ Documentation"
    label: "documentation"

exclude-labels:
  - "skip-changelog"

autolabeler:
  - label: "chore"
    branch:
      - '/chore\/.+/'
  - label: "documentation"
    files:
      - "*.md"
    branch:
      - '/doc\/.+/'
  - label: "bug"
    branch:
      - '/fix\/.+/'
      - '/Fix\/.+/'
  - label: "enhancement"
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
      - '/Feat\/.+/'

template: |
  ## Changes

  $CHANGES
