apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: helloworld
profiles:
  - name: "local"
    build:
      artifacts:
        - image: smana/helloworld
          docker:
            target: "tester"
          sync:
            manual:
              - dest: "."
                src: "helloworld/**/*.html"
    test:
      - image: smana/helloworld
        structureTests:
          - "./tests/structure/*"
    deploy:
      helm:
        releases:
          - name: helloworld
            chartPath: charts/helloworld
            namespace: demo
            createNamespace: True
            wait: True
            setValues:
              vaultInject:
                enabled: True
            artifactOverrides:
              image: "smana/helloworld"
