apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
spec:
  releaseName: web
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "8.5.5"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    fullnameOverride: "webserver"
