apiVersion: v1
data:
    password: ENC[AES256_GCM,data:VTSkFgbyR9L/4ug7RAdNPA==,iv:LSJYXZ1mqmVhVO0FjtY7pjclTxqgiOaMK8tn+J6nBBw=,tag:wgnBwbOgldoXPIsuxl0vtw==,type:str]
    user: ENC[AES256_GCM,data:GrHxsn4v0W8=,iv:yavMeJDClWwF/YpQ2XiUuswRgzNACs2OPWrhcv87668=,tag:NA/WB4uOcbdtPzJdhVlPBg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: prod-helloworld
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-12T15:57:03Z"
    mac: ENC[AES256_GCM,data:MKEW4NfAve69AyxWxD2OPt9L82xcTw8C11NmqhGNCUs58dZy/MDme7ifiEV2NnRGl60BMMXlxExm2VdYwHcvdkzYiILfmWrtpi2lHjT5o0Q1ufMDr+KZWX5AX9bAC7bMEUSzcIadn2cFHWRw9VqspBX+H5nMtctbrZArgJdSGIg=,iv:TTRdgftf/QB+W4OcxRks9pyWbq6XN/lYBr1K4VppjBE=,tag:X7AW/flkzmMogEkop+X2tQ==,type:str]
    pgp:
        - created_at: "2021-07-12T15:57:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3EM9k0/DEgRARAAtdAUEI5SC33coGNZzIJcRoCuzz28G8Wl4NV3kE2l3iVJ
            cyGh3gR/2oktdoluiTymEkCc5BusqML79GfJXKg4RI/x9tO383zlzKCpLTYKpC/5
            WsipbCz8Z5jyWPXv3huH9INAnloX5PwYk2N7C+mM/cyZtorJ7mymMuEZKzKk5J3b
            quZeb6VL0I301frpgbfqGAklo/3jypWwU+Rdu4WUxduRXX8z4YdNdzv9PazUu1wE
            /nlLPMYGw9jUkt0UejS1KzOfPu4YrmNlYOaPsuuWtIUjxTZA0g1iN4UqWUriCN82
            S82e0MAsdsHTUyXXD+VJAAzM9ahQFOHJmRDIxhRMwbt0g7nYYg+J9B5TPeAsXQi+
            pdhgpvRlz5IpWJ3Q+eIgev9ciLP4n30ri69aLJS/v64JzFtuVVW2aXlTwaf0ATwf
            QQbtyE0p1f9mh1vi8zLiZOWnA8jLe52M7IcNWg5v1h23XryYEyck8oZVjrvmP2HI
            KYMbw/2SWAATJwUhbQm/hLhG8sUyIINCMkKecUaTUiiE92pzCu/5HeDCV+YJCFn9
            RU7ZzPbChq0jB+YthU2156gfWK9NcvLSERiGX/ShyzhkW4MXnoJZyD6sZLWrfJGx
            0BXLQJWx9/r7y2wn1vOKkuHa/bfA5ws82mDFeDpXB5Z3DSCxYdSnL+Q9kF5LB8LS
            XgFElrcipVKhX7CThmkptECilua/8WzhYN1pZeTx6LfiwOePoUHY4lx5mEUlyGNL
            5IUyoyXMEnFzlO2bWK71d75J4+CGKSNhaQE903t4oOFtdPtmSM6V8gbalgeEodQ=
            =3146
            -----END PGP MESSAGE-----
          fp: 460A6C9C6EE7FC53644563E5989F2E56CA5E3488
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
