apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus
spec:
  releaseName: kube-prometheus
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: "16.11.0"
  interval: 10m0s
  install:
    remediation:
      retries: 3
  values:
    fullnameOverride: "kube-prometheus"
