name: Tests code and manifests

on:
  pull_request:
    branches:
      - main
      - staging

jobs:
  quality:
    name: "Check code quality ✨"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Dockerfile lint
        uses: hadolint/hadolint-action@v1.5.0

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -r test_requirements.txt

      - name: Format
        run: black -l 79 --py36 --check helloworld

      - name: Check code complexity
        run: xenon --max-absolute=B --max-modules=B --max-average=A helloworld

      - name: Python lint
        run: pylint --reports=n helloworld

      - name: Check Kubernetes yamls
        uses: stefanprodan/kube-tools@v1.5.0
        with:
          helmv3: 3.2.1
          command: |
            helmv3 template ./charts/helloworld | kubeval --strict

  tests:
    name: "Run tests 🧐"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -r test_requirements.txt

      - name: Unit tests
        run: pytest tests
