name: Tests code and manifests

on:
  pull_request:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -r test_requirements.txt
          pip install -e .

      - name: Install Trivy (Vulns scan)
        run: |
          export VERSION=$(curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
          wget https://github.com/aquasecurity/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-64bit.tar.gz
          tar zxvf trivy_${VERSION}_Linux-64bit.tar.gz

      - name: Format
        run: black -l 79 --py36 --check helloworld

      - name: Complexity
        run: xenon --max-absolute=B --max-modules=B --max-average=A helloworld

      - name: Lint
        run: pylint --reports=n helloworld

      - name: Unit tests
        run: pytest tests

      - name: Check Kubernetes yamls
        uses: stefanprodan/kube-tools@v1.5.0
        with:
          helmv3: 3.2.1
          command: |
            helmv3 template ./charts/helloworld | kubeval --strict
