name: Deploy when merging master

on:
  pull_request:
    branches:
      - "master"
    types:
      - "closed"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Create Helm charts values
      uses: stefanprodan/kube-tools@v1.5.0
      with:
        command: |
          yq eval -i '.spec.values.image="smana/helloworld:sha-'${GITHUB_SHA:0:7}'"' ./charts/helloworld/values.yaml

    - name: Automatically commit Helm charts changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply automatic charts changes
        file_pattern: flux/*
        commit_user_name: Github Actions Bot
        commit_user_email: smainklh@gmail.com
        commit_author: Actions bot <smainklh@gmail.com>
